export const path = {
    home: '/',
    about: '/about',
    login: '/login',
    signUp: '/signUp',
    admin: '/admin',
    manageUser: '/admin/manageUser',
    manageExam: '/admin/manageExam',
    createExam: '/createExam',
    editExam: '/editExam/:examId',
    verification: '/verification/:examId',
    startExam: '/exam/:examId',
    resultExam: '/result/:examId',
    myExam: '/myExam',
    myLoveExam: '/favorite',
    myDoExam: '/mydoExam',
    ratings: '/ratings/:examId',
    setting: '/settings/personal',
    forgotPassword: "/forgot/password",
    notFound: '/404',
}
