export const path = {
    home: '/',
    about: '/about',
    login: '/login',
    signUp: '/signUp',
    admin: '/admin',
    manageUser: '/admin/manageUser',
    manageExam: '/admin/manageExam',
    createExam: '/createExam',
    editExam: '/editExam/:examId',
    verification: '/verification/:email/:nameUser/:examId',
    startExam: '/exam/:email/:nameUser/:examId',
    resultExam: '/result/:email/:nameUser/:examId/:copyScoreId',
    myExam: '/myExam',
    myLoveExam: '/favorite',
    myDoExam: '/mydoExam',
    ratings: '/ratings/:examId',
    setting: '/settings/personal',
    forgotPassword: '/forgot/password',
    notFound: '/404',
}
